export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Dashboard } from './Dashboard'
export { default as Trips } from './Trips'
export { default as Destinations } from './Destinations'
export { default as Activities } from './Activities'